### ISSUE TITLE
Kalman filter 

### ISSUE THREAD

**Issue by saedelman** [nopnop2002/esp-idf-lsm6ds3#2]
The pitch and roll calculation in the Kalman demo are not actually derived from the Kalman filter. The Kalman code is completely inmaterial here.

roll = atan(accY / sqrt(accX * accX + accZ * accZ)) * RAD_TO_DEG;
pitch = atan2(-accX, accZ) * RAD_TO_DEG;

**Comment by nopnop2002** [comment]
Thank you for your report.
Changed to use filter results.

**Comment by saedelman** [comment]
Thank you.
